// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Padel.Web.Mvc.Areas.Admin.Controllers
{
    public partial class JugadoresController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected JugadoresController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult _Listado()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._Listado);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult _Modificar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._Modificar);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public JugadoresController Actions { get { return MVC.Admin.Jugadores; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Jugadores";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Jugadores";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string _Listado = "_Listado";
            public readonly string _Modificar = "_Modificar";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string _Listado = "_Listado";
            public const string _Modificar = "_Modificar";
        }


        static readonly ActionParamsClass__Listado s_params__Listado = new ActionParamsClass__Listado();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass__Listado _ListadoParams { get { return s_params__Listado; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass__Listado
        {
            public readonly string page = "page";
            public readonly string size = "size";
        }
        static readonly ActionParamsClass__Modificar s_params__Modificar = new ActionParamsClass__Modificar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass__Modificar _ModificarParams { get { return s_params__Modificar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass__Modificar
        {
            public readonly string jugadoresModelView = "jugadoresModelView";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Editar = "Editar";
                public readonly string Index = "Index";
            }
            public readonly string Editar = "~/Areas/Admin/Views/Jugadores/Editar.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Jugadores/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_JugadoresController : Padel.Web.Mvc.Areas.Admin.Controllers.JugadoresController
    {
        public T4MVC_JugadoresController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void _ListadoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page, int? size);

        public override System.Web.Mvc.ActionResult _Listado(int? page, int? size)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._Listado);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "size", size);
            _ListadoOverride(callInfo, page, size);
            return callInfo;
        }

        partial void _ModificarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.List<Padel.Web.Mvc.Areas.Admin.Controllers.ViewModels.Jugadores.JugadorViewModel> jugadoresModelView);

        public override System.Web.Mvc.ActionResult _Modificar(System.Collections.Generic.List<Padel.Web.Mvc.Areas.Admin.Controllers.ViewModels.Jugadores.JugadorViewModel> jugadoresModelView)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._Modificar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "jugadoresModelView", jugadoresModelView);
            _ModificarOverride(callInfo, jugadoresModelView);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
