// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Padel.Web.Mvc.Controllers
{
    public partial class TorneosController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TorneosController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult _TorneosPorJugador()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._TorneosPorJugador);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult _CrearEquipoParaTorneo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._CrearEquipoParaTorneo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult _DesapuntanteDelTorneo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._DesapuntanteDelTorneo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult _PagaElTorneoConPuntos()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._PagaElTorneoConPuntos);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TorneosController Actions { get { return MVC.Torneos; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Torneos";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Torneos";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string _TorneosPorJugador = "_TorneosPorJugador";
            public readonly string _CrearEquipoParaTorneo = "_CrearEquipoParaTorneo";
            public readonly string _DesapuntanteDelTorneo = "_DesapuntanteDelTorneo";
            public readonly string _PagaElTorneoConPuntos = "_PagaElTorneoConPuntos";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string _TorneosPorJugador = "_TorneosPorJugador";
            public const string _CrearEquipoParaTorneo = "_CrearEquipoParaTorneo";
            public const string _DesapuntanteDelTorneo = "_DesapuntanteDelTorneo";
            public const string _PagaElTorneoConPuntos = "_PagaElTorneoConPuntos";
        }


        static readonly ActionParamsClass__TorneosPorJugador s_params__TorneosPorJugador = new ActionParamsClass__TorneosPorJugador();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass__TorneosPorJugador _TorneosPorJugadorParams { get { return s_params__TorneosPorJugador; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass__TorneosPorJugador
        {
            public readonly string tipo = "tipo";
        }
        static readonly ActionParamsClass__CrearEquipoParaTorneo s_params__CrearEquipoParaTorneo = new ActionParamsClass__CrearEquipoParaTorneo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass__CrearEquipoParaTorneo _CrearEquipoParaTorneoParams { get { return s_params__CrearEquipoParaTorneo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass__CrearEquipoParaTorneo
        {
            public readonly string idEquipo = "idEquipo";
            public readonly string idJugador = "idJugador";
            public readonly string idTorneo = "idTorneo";
            public readonly string idCategoria = "idCategoria";
            public readonly string terminosAceptados = "terminosAceptados";
        }
        static readonly ActionParamsClass__DesapuntanteDelTorneo s_params__DesapuntanteDelTorneo = new ActionParamsClass__DesapuntanteDelTorneo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass__DesapuntanteDelTorneo _DesapuntanteDelTorneoParams { get { return s_params__DesapuntanteDelTorneo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass__DesapuntanteDelTorneo
        {
            public readonly string idEquipoCategoria = "idEquipoCategoria";
        }
        static readonly ActionParamsClass__PagaElTorneoConPuntos s_params__PagaElTorneoConPuntos = new ActionParamsClass__PagaElTorneoConPuntos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass__PagaElTorneoConPuntos _PagaElTorneoConPuntosParams { get { return s_params__PagaElTorneoConPuntos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass__PagaElTorneoConPuntos
        {
            public readonly string idEquipoCategoria = "idEquipoCategoria";
            public readonly string tipo = "tipo";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Views/Torneos/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_TorneosController : Padel.Web.Mvc.Controllers.TorneosController
    {
        public T4MVC_TorneosController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void _TorneosPorJugadorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string tipo);

        public override System.Web.Mvc.ActionResult _TorneosPorJugador(string tipo)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._TorneosPorJugador);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tipo", tipo);
            _TorneosPorJugadorOverride(callInfo, tipo);
            return callInfo;
        }

        partial void _CrearEquipoParaTorneoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? idEquipo, int? idJugador, int? idTorneo, int? idCategoria, bool? terminosAceptados);

        public override System.Web.Mvc.ActionResult _CrearEquipoParaTorneo(int? idEquipo, int? idJugador, int? idTorneo, int? idCategoria, bool? terminosAceptados)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._CrearEquipoParaTorneo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "idEquipo", idEquipo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "idJugador", idJugador);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "idTorneo", idTorneo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "idCategoria", idCategoria);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "terminosAceptados", terminosAceptados);
            _CrearEquipoParaTorneoOverride(callInfo, idEquipo, idJugador, idTorneo, idCategoria, terminosAceptados);
            return callInfo;
        }

        partial void _DesapuntanteDelTorneoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int idEquipoCategoria);

        public override System.Web.Mvc.ActionResult _DesapuntanteDelTorneo(int idEquipoCategoria)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._DesapuntanteDelTorneo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "idEquipoCategoria", idEquipoCategoria);
            _DesapuntanteDelTorneoOverride(callInfo, idEquipoCategoria);
            return callInfo;
        }

        partial void _PagaElTorneoConPuntosOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int idEquipoCategoria, int tipo);

        public override System.Web.Mvc.ActionResult _PagaElTorneoConPuntos(int idEquipoCategoria, int tipo)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._PagaElTorneoConPuntos);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "idEquipoCategoria", idEquipoCategoria);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tipo", tipo);
            _PagaElTorneoConPuntosOverride(callInfo, idEquipoCategoria, tipo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
