// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Padel.Web.Mvc.Controllers
{
    public partial class UsuariosController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UsuariosController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult _Registrar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._Registrar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Entrar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Entrar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult _Entrar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._Entrar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ValidarTelefonoUnico()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ValidarTelefonoUnico);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ValidarEmailUnico()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ValidarEmailUnico);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult _JugadorPorNombre()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._JugadorPorNombre);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UsuariosController Actions { get { return MVC.Usuarios; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Usuarios";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Usuarios";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string _Registrar = "_Registrar";
            public readonly string Entrar = "Entrar";
            public readonly string _Entrar = "_Entrar";
            public readonly string ValidarTelefonoUnico = "ValidarTelefonoUnico";
            public readonly string ValidarEmailUnico = "ValidarEmailUnico";
            public readonly string Logout = "Logout";
            public readonly string _JugadorPorNombre = "_JugadorPorNombre";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string _Registrar = "_Registrar";
            public const string Entrar = "Entrar";
            public const string _Entrar = "_Entrar";
            public const string ValidarTelefonoUnico = "ValidarTelefonoUnico";
            public const string ValidarEmailUnico = "ValidarEmailUnico";
            public const string Logout = "Logout";
            public const string _JugadorPorNombre = "_JugadorPorNombre";
        }


        static readonly ActionParamsClass__Registrar s_params__Registrar = new ActionParamsClass__Registrar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass__Registrar _RegistrarParams { get { return s_params__Registrar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass__Registrar
        {
            public readonly string usuarioModelView = "usuarioModelView";
        }
        static readonly ActionParamsClass_Entrar s_params_Entrar = new ActionParamsClass_Entrar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Entrar EntrarParams { get { return s_params_Entrar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Entrar
        {
            public readonly string returnUrl = "returnUrl";
        }
        static readonly ActionParamsClass__Entrar s_params__Entrar = new ActionParamsClass__Entrar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass__Entrar _EntrarParams { get { return s_params__Entrar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass__Entrar
        {
            public readonly string usuarioModelView = "usuarioModelView";
            public readonly string returnUrl = "returnUrl";
        }
        static readonly ActionParamsClass_ValidarTelefonoUnico s_params_ValidarTelefonoUnico = new ActionParamsClass_ValidarTelefonoUnico();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValidarTelefonoUnico ValidarTelefonoUnicoParams { get { return s_params_ValidarTelefonoUnico; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValidarTelefonoUnico
        {
            public readonly string telefonoMovil = "telefonoMovil";
        }
        static readonly ActionParamsClass_ValidarEmailUnico s_params_ValidarEmailUnico = new ActionParamsClass_ValidarEmailUnico();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValidarEmailUnico ValidarEmailUnicoParams { get { return s_params_ValidarEmailUnico; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValidarEmailUnico
        {
            public readonly string email = "email";
        }
        static readonly ActionParamsClass__JugadorPorNombre s_params__JugadorPorNombre = new ActionParamsClass__JugadorPorNombre();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass__JugadorPorNombre _JugadorPorNombreParams { get { return s_params__JugadorPorNombre; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass__JugadorPorNombre
        {
            public readonly string nombreJugador = "nombreJugador";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Entrar = "Entrar";
            }
            public readonly string Entrar = "~/Views/Usuarios/Entrar.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UsuariosController : Padel.Web.Mvc.Controllers.UsuariosController
    {
        public T4MVC_UsuariosController() : base(Dummy.Instance) { }

        partial void _RegistrarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Padel.Web.Mvc.Controllers.ViewModels.Usuarios.UsuarioRegistrarModelView usuarioModelView);

        public override System.Web.Mvc.ActionResult _Registrar(Padel.Web.Mvc.Controllers.ViewModels.Usuarios.UsuarioRegistrarModelView usuarioModelView)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._Registrar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "usuarioModelView", usuarioModelView);
            _RegistrarOverride(callInfo, usuarioModelView);
            return callInfo;
        }

        partial void EntrarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string returnUrl);

        public override System.Web.Mvc.ActionResult Entrar(string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Entrar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            EntrarOverride(callInfo, returnUrl);
            return callInfo;
        }

        partial void _EntrarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Padel.Web.Mvc.Controllers.ViewModels.Usuarios.UsuarioEntrarModelView usuarioModelView, string returnUrl);

        public override System.Web.Mvc.ActionResult _Entrar(Padel.Web.Mvc.Controllers.ViewModels.Usuarios.UsuarioEntrarModelView usuarioModelView, string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._Entrar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "usuarioModelView", usuarioModelView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            _EntrarOverride(callInfo, usuarioModelView, returnUrl);
            return callInfo;
        }

        partial void ValidarTelefonoUnicoOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int? telefonoMovil);

        public override System.Web.Mvc.JsonResult ValidarTelefonoUnico(int? telefonoMovil)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ValidarTelefonoUnico);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "telefonoMovil", telefonoMovil);
            ValidarTelefonoUnicoOverride(callInfo, telefonoMovil);
            return callInfo;
        }

        partial void ValidarEmailUnicoOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string email);

        public override System.Web.Mvc.JsonResult ValidarEmailUnico(string email)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ValidarEmailUnico);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "email", email);
            ValidarEmailUnicoOverride(callInfo, email);
            return callInfo;
        }

        partial void LogoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Logout()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Logout);
            LogoutOverride(callInfo);
            return callInfo;
        }

        partial void _JugadorPorNombreOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string nombreJugador);

        public override System.Web.Mvc.ActionResult _JugadorPorNombre(string nombreJugador)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._JugadorPorNombre);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nombreJugador", nombreJugador);
            _JugadorPorNombreOverride(callInfo, nombreJugador);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
